### ISSUE TITLE
Version flag ?

### ISSUE THREAD

**Issue by roblabla** [reswitched/SwIPC#8]
It'd be nice if we could have a version flag in the various IPC cmds so we know when they were added (and maybe removed).

Something like an `"added": "2.0.0"` (which defaults to 1.0.0) and `"removed": "2.0.0"` (if not present, then it wasn't removed yet) in each cmds ?

**Comment by hthh** [comment]
The data required for this can be found at https://gist.github.com/hthh/bb896c743878a2c0c337f41febdc0426  (warning: **huge** page, you can `git clone` that URL to download the separate files and browse more easily)

The problem is much more complicated than it seems at first as unstable APIs can change in literally any way. Sometimes arguments or names are the only thing to change. But worse, some commands change ID (replacing other existing IDs, so "some IDs change command" is also true), e.g. commands 6/7 of `nn::usb::hs::IClientRootSession`.

Also, unfortunately, we can't know what's part of the public API until it changes, unless we emulate and trace third party apps and find the IPC calls they make. Virtual calls make static analysis hard/impractical in many cases.

That doesn't mean it's a lost cause - it'd be really good to have this data for thus-far-stable commands, and maybe an `"unstable": true` for things known to change in complex ways.

**Comment by roblabla** [comment]
So, some bike-shedding on adding this in SwIPC document itself : 

```
interface meh {
    # Available everywhere
    [0] Everywhere();
    # Introduced on 2.0.0, never removed
    [1, 2.0.0-] 2_0_0_and_up();
    # Introduced in 1.0.0, removed in 2.0.0
    [2, -2.0.0] 1_0_0_only();
    # Introduced in 3.0.0, removed in 3.0.2
    [3, 3.0.0-3.0.2] version_range();
}
```

Obviously the same command ID may be reused on different version range, so long as there's no overlap (useful if command parameters changed for instance).

People can then make their own judgement on whether to rely on a function knowing where it's available.

**Comment by hthh** [comment]
I feel very differently about this. Since you're implementing it you can do it your way, I just thought I'd share my thoughts in case.

I like the `[0]` look to make the command ID clear, and find having other numbers in there a bit hard to read. I was thinking about adding a more generic extension, a concept inspired by GNU C's `__attribute__` using syntax inspired by Python's decorators. (This might allow us to add other data in the future, such as citations for where the method name comes from, or parameter bytes-in/bytes-out where we don't have full parameter information, or just want to assert they're the same to catch mistakes.)

I'd also prefer ranges to be inclusive (as I think is the convention on switchbrew), and to avoid open intervals (because the `-` looks somewhat like a minus sign which I find confusing to read as 'and higher numbers').

```
interface meh {
    # Available everywhere
    [0] Everywhere();
    # Introduced on 2.0.0, never removed
    @version(2.0.0+)
    [1] 2_0_0_and_up();
    # Introduced in 1.0.0, removed in 2.0.0
    @version(1.0.0)
    [2] 1_0_0_only();
    # Introduced in 3.0.0, removed in 3.0.2
    @version(3.0.0-3.0.1)
    [3] version_range();
}
```

Again, since you're doing all the actual work, feel free to ignore my bike-shedding, and nice work! :)

**Comment by roblabla** [comment]
That seems like a good idea ! And I'm posting here to get this kind of feedback, so thanks :).

**Comment by roblabla** [comment]
Thought: We have version flags for cmds, but not for interfaces or service names. That'd be good to have.

```
interface meh is one, two, @version(2.0.0+) three {}
```

This looks kinda gross, but could work. Another possibility (although a fairly major departure):

```
@provides(one)
@provides(two)
@provides(three, 2.0.0+)
interface meh {}
```
